# Generated by Django 5.1.3 on 2025-06-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_listing_image_listing_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner_name',
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/listing_images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('sharing', 'Sharing')], max_length=10),
        ),
    ]
