# Generated by Django 5.1.3 on 2025-06-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_listing_owner_name_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
