# Generated by Django 5.1.3 on 2025-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_delete_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('pg', 'PG'), ('hostel', 'Hostel')], max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('sharing', 'Sharing')], max_length=10)),
                ('beds', models.IntegerField()),
                ('contact_info', models.CharField(max_length=15)),
                ('collage', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/listing_images/')),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('wife', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('home_service', models.CharField(max_length=50)),
                ('meals', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('type_room', models.CharField(choices=[('ac', 'AC'), ('non-ac', 'Non-AC')], max_length=10)),
                ('laundry', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
            ],
        ),
    ]
