# Generated by Django 5.1.3 on 2025-06-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='beds',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=50),
        ),
    ]
