# Generated by Django 5.1.3 on 2025-06-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_listing_beds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='collage',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='wife',
            new_name='wifi',
        ),
    ]
