# Generated by Django 5.1.3 on 2025-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_collage_listing_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hostel_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
