# Generated by Django 5.1.3 on 2025-06-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_listing_hostel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='hostel_name',
            field=models.CharField(max_length=100),
        ),
    ]
